language: node_js
node_js:
- 4.0
before_install:
- npm install -g gulp-cli
install:
- npm install
after_success:
- chmod +x ./bin/create-release-tag.sh
- "./bin/create-release-tag.sh"
branches:
  except:
  - "/^v/"
deploy:
  provider: heroku
  api_key:
    secure: TtE3AyDX2KaM/dZGt6R4Hbc9NZC2+0/8njr6MwM8Zd9RY0iPNSSLDFucpyjbmPWJtE3PhCIxprimdzQk1MnV1yRMuJ1O2CH9Cjcq2mc8Gfn8H0bXpuOd5Q4NyE9Nx5lG/GQ7ASbwba3wyQ2boG1pon+Xh5Ib3AARbex8AUNOPs0s03Q/vXNvtnKAzTke31f38l1QyGmDNVvyS2+1HA3iTDS2UEn5X3ms/CM8iTJNaDuSf247vheLfGnVNn8+PPk2wop8na8NTfTjbp+VMItXY1FduHw1ehH6LcDytS1RvULC1p2jZmZc66croq1DIUdygS+MmYQ9XTRLYDU6EhX288NnenN3GgWtW9DjQiPEIOXLdyrKo5tNbXYTWfR3hw5yB6tIK+46ogP/yPO5HTm/Jirz/0ogYJ7iPL3C8zeAxGMa/NcCJVvBhSRTQEHFQNCTTrNxgYf0AiQSp0b12TtLm6C4q2B+OfbihQMf9i4RdOynmb6Pwxbf0yQfP37hBNgy9rw689nTvy4oYI/oO18M9CwdaD4LfOkB3po12EFvmmKgjGPpkps2rofDhgFHo1/t3iT05ql+L6kykB0ARMgOjmkWR0cPWy+E+7yUvE76TLitP4wJzSk3tsc79VNygSBxWASYm1i6302d4pFIP0a3USbv6HX0aDuXW/oWQyGl4Sw=
  app: lcc-gov
  on: master
notifications:
  email: false
sudo: false
